name: conf
description:
  Schema based configuration management that supports combining multiple
  configuration sources.
version: 0.2.0
repository: https://github.com/blaugold/conf
issue_tracker: https://github.com/blaugold/conf/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  meta: ^1.8.0
  path: ^1.7.0
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.0
