name: conf
description:
  Schema based configuration management that supports combining multiple
  configuration sources.
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  meta: ^1.8.0

dev_dependencies:
  test: ^1.21.0
